#!/bin/bash
# Macaroni - MAC Address Changer

# Choose a random MAC prefix brand
file="$(find mac-prefix/ -type f | shuf -n 1)"

# Choose a random MAC prefix from the list
prefix="$(shuf -n 1 $file)"

# Randomly complete the MAC Address
host="$(printf '%02x' $((0x$(od /dev/urandom -N1 -t x1 -An | cut -c 2-) & 0xFE | 0x02)); od /dev/urandom -N2 -t x1 -An | sed 's/ /:/g')"

# Changes your MAC Address
ifconfig wlan0 down && ifconfig wlan0 hw ether $prefix:$host && ifconfig wlan0 up
